dependencies:
  build:
    - python:3.6.3

build_targets:
  - name: default
    commands:
      - environ 
      - python -c "print('DONE')"

ci:
  builds:
    - name: default
      build_target: default
